apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dg21
  namespace: oracle-dg
spec:
  serviceName: "dg21"   # must match the headless service
  replicas: 1
  selector:
    matchLabels:
      app: dg21
  template:
    metadata:
      labels:
        app: dg21
    spec:
      containers:
      - name: dg21
        image: man2001thcs/oracle-db:19.3.0-ee-dg
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1521
        env:
        - name: CONTAINER_NAME
          value: "DG21"
        - name: DG_CONFIG
          value: "DG1"
        - name: DG_TARGET
          value: "DG11"
        - name: ORACLE_PDB
          value: "DG11PDB1"
        - name: ORACLE_PWD
          value: "oracleVipPro123"
        - name: ORACLE_SID
          value: "DG11"
        - name: DB_UNQNAME
          value: "DG21"
        - name: ROLE
          value: "STANDBY"
        volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: dg21-storage
          subPath: oracle-dg21   # Fixed subPath to match this instance
        - mountPath: /opt/oracle/scripts/tnsnames.ora
          name: tnsnames-volume
          subPath: tnsnames.ora
      volumes:                      # ConfigMap volume goes here
      - name: tnsnames-volume
        configMap:
          name: tnsnames-config
  volumeClaimTemplates:
  - metadata:
      name: dg21-storage
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: oracle-db-sc
      resources:
        requests:
          storage: 70Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dg21
  namespace: oracle-dg
spec:
  type: ClusterIP
  selector:
    app: dg21
  ports:
  - name: listener
    port: 1521
    targetPort: 1521
---
apiVersion: v1
kind: Service
metadata:
  name: dg21-np
  namespace: oracle-dg
spec:
  type: NodePort
  selector:
    app: dg21
  ports:
  - name: listener
    port: 1521
    targetPort: 1521
    nodePort: 32012
