spring.application.name=gemini
gemini.apikey=AIzaSyAHCLU1Oar8FwcdrptCAlE2d9hMUfQSPEg
gemini.project=gen-lang-client-0012727179

spring.data.redis.host=${REDIS_HOST:10.168.4.131}
spring.data.redis.port=${REDIS_PORT:32090}
spring.data.redis.password=${REDIS_PASS:VNPT@1234!}