apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-db-pv-01
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: hishn-oracle-database-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/k8s-database/db-setup/Oracle/data/pv-01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - eheatlthbvtmermapigw01101684131-db
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-db-pvc-01
  namespace: test-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: hishn-oracle-database-storage
