{
 "title": "OpenTelemetry Overview [TEST]",
 "description": "A language-agnostic application performance management(APM) with OpenTelemetry, Grafana, and Prometheus.",
 "tags": [
  "VNPT",
  "Cloud",
  "Observability"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "3m",
 "templating": {
  "list": [
   { "name": "metric_datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "trace_datasource", "label": "Tempo-Datasource", "query": "tempo" },
   { "name": "service", "label": "Service", "query": { "query": "label_values(exported_job)" } },
   { "name": "route", "label": "Route", "query": { "query": "label_values(http_route)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Request",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\", exported_job=\"$service\"}[$interval])))\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests Method Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_request_method=\"GET\"}[$interval]))  ) or vector(0)",
     "legendFormat": "GET"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_request_method=\"POST\"}[$interval]))  ) or vector(0)",
     "legendFormat": "POST"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_request_method=\"PUT\"}[$interval]))  ) or vector(0)",
     "legendFormat": "PUT"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_request_method=\"DELETE\"}[$interval]))  ) or vector(0)",
     "legendFormat": "DELETE"
    },
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_request_method=\"PATCH\"}[$interval]))  ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "description": "request amount distribution",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(traces_span_metrics_duration_milliseconds_count{span_kind=\"SPAN_KIND_SERVER\", service_name=\"$service\"}[5m])) by (span_name))\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Time Distribution",
   "type": "piechart",
   "description": "cumulative latency distribution",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(traces_span_metrics_duration_milliseconds_bucket{service_name=\"$service\"}) by(span_name))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "gauge",
   "description": "overall request rate per minute over last 3 minutes",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_count {http_route=~\"$route\", exported_job=\"$service\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "description": "percentage of HTTP status 5xx in all requests",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(traces_service_graph_request_failed_total{})/sum(traces_service_graph_request_client_seconds_count{})) or vector(0)"
    }
   ]
  },
  {
   "title": "Total 2XX Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_response_status_code=~\"^2.*\"}[$interval]))) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total 3XX Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_response_status_code=~\"^3.*\"}[$interval]))) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total 4XX Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_response_status_code=~\"^4.*\"}[$interval]))) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total 5XX Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_request_duration_seconds_count{http_route=~\"$route\",exported_job=\"$service\", http_response_status_code=~\"^5.*\"}[$interval]))) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service\"}"
    }
   ]
  },
  {
   "title": "3s < Duration <10s",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "3s",
       "valueType": "duration"
      },
      {
       "id": "max-duration",
       "operator": "<",
       "tag": "duration",
       "value": "10s",
       "valueType": "duration"
      },
      { "id": "8fbbcd0f", "operator": "=", "scope": "span" }
     ],
     "limit": 10,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service\" &&  duration<10s && duration>3s}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Duration > 10s",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "filters": [
      {
       "id": "7399e90f",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "10s",
       "valueType": "duration"
      },
      {
       "id": "max-duration",
       "operator": "<",
       "tag": "duration",
       "value": "",
       "valueType": "duration"
      }
     ],
     "limit": 10,
     "query": "{resource.service.name=\"$service\" && duration>10s}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Span-Level Exception Messages With Duration > 1s",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "filters": [
      { "id": "89e330c6", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service\" && duration > 1 && .http.response.status_code != 200} ",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Database  Statement With Duration > 1s",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "filters": [
      {
       "id": "filter1",
       "key": "db.name",
       "operator": "=",
       "scope": "span",
       "value": "apm_db"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service\" && span.db.name!=\"\" && span.db.statement!=\"\" && duration > 1s}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "request rate per minute over last 3 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "topk(3,\n  sum(rate(traces_span_metrics_duration_milliseconds_count{service_name=\"$service\"}[5m])) by (span_name)\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "description": "by route and http status code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(traces_span_metrics_duration_milliseconds_sum{\"service_name\"=\"$service\"} / traces_span_metrics_duration_milliseconds_count{\"service_name\"=\"$service\"}))",
     "legendFormat": "[{{http_status_code}}] {{span_name}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "description": "Details of each API",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_route=~\"$route\"}[3m]) * 60) \r\nby (http_request_method, http_route)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_bucket{http_route=~\"$route\"}[3m])) by (le, http_request_method, http_route))\r\n"
    },
    {
     "expr": "sum(http_server_request_duration_count{http_response_status_code!~\"2.*|3.*\", http_route=\"$route\"}) \r\n/\r\nsum(http_server_request_duration_count{http_route=\"$route\"}) \r\nby(http_request_method, http_route)\r\n"
    }
   ]
  }
 ]
}