apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-01
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: loki-sc
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/hishn-monitoring/loki/pv-01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - eheatlthbvtmermapigw01101684131-db
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: monitoring-stuff
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: loki-sc
