apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-worker
  namespace: emr-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n8n-worker
  template:
    metadata:
      labels:
        app: n8n-worker
    spec:
      containers:
        - name: n8n-worker
          image: man2001thcs/n8n-db-tool:20251015
          command: ["n8n", "worker"]
          env:
            - name: N8N_MODE
              value: worker

            - name: EXECUTIONS_MODE
              value: queue

            - name: QUEUE_BULL_REDIS_HOST
              value: redis-service.emr-cloud.svc.cluster.local

            - name: QUEUE_BULL_REDIS_PORT
              value: "6379"

            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: quick-postgres-service
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_USER
              value: n8n
            - name: DB_POSTGRESDB_PASSWORD
              value: n8npassword

            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: encryptionKey