apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-01-pvc
  namespace: test-database
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-02-pvc
  namespace: test-database
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: 10Gi
