apiVersion: v1
kind: Pod
metadata:
  name: pv-helper
  namespace: test-database
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: pv-01
      mountPath: /opt/pv-01
    - name: pv-02
      mountPath: /opt/pv-02
  volumes:
  - name: pv-01
    persistentVolumeClaim:
      claimName: postgres-01-pvc
  - name: pv-02
    persistentVolumeClaim:
      claimName: postgres-02-pvc
