---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replica
  namespace: test-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - eheatlthbvtmermapigw01101684131-db
      containers:
      - name: postgres-replica
        image: man2001thcs/postgres-15:20240819
        env:
        - name: PGUSER
          value: replicator
        - name: PGPASSWORD
          value: "123456"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-replica-data
        command:
        - bash
        - -c
        - |
          if [ ! -f /var/lib/postgresql/data/postgresql.conf ]; then
            initdb -D /var/lib/postgresql/data
          fi

          echo "host replication replicator 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf 

          mkdir -p /var/lib/postgresql/temp_data
          if pg_basebackup --pgdata=/var/lib/postgresql/temp_data -R --slot=replication_slot --host=10.168.4.131 --port=32020; then
            echo 'Backup from primary done, moving data to final location...'
            rm -rf /var/lib/postgresql/data/*
            mv /var/lib/postgresql/temp_data/* /var/lib/postgresql/data/
            rmdir /var/lib/postgresql/temp_data
          fi
          chmod 0700 /var/lib/postgresql/data
          exec postgres
      volumes:
      - name: postgres-replica-data
        persistentVolumeClaim:
          claimName: postgres-replica-pvc
